import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Swiper, { loadSwiper } from '../components/Swiper'
import Movie, { loadMovie } from '../components/Movie'
import Layout from '../components/Layout'

export default function Home({ swiper, movies }: any) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <Swiper swiper={swiper} />
          <Movie movies={movies} />
        </Layout>
      </main>
    </>
  )
}

export async function getStaticProps(context: any) {
  // 获取轮播图
  const { data: swiper } = await loadSwiper()
  // 获取电影列表
  const { data: movies } = await loadMovie()
  return {
    props: {
      swiper,
      movies
    }
  }
}
